spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gogz
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: baeldung

resilience4j.retry:
  instances:
    hello-retry:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.lang.RuntimeException
      #  ignoreExceptions:
      #   - com.jsession4d.samplerest.BusinessException
server:
  kafka: "localhost:9092"